[tool.pytest.ini_options]
pythonpath = "."
addopts = "-v --cov=app --cov-report=term-missing"
testpaths = ["tests"]
asyncio_mode = "auto"
env = [
    "DATABASE_URL=sqlite+aiosqlite:///:memory:",
    "SECRET_KEY=test_secret_key",
    "GOOGLE_CLIENT_ID=test_client_id",
    "GOOGLE_CLIENT_SECRET=test_client_secret"
]
